### ISSUE TITLE
Missing Dependency: Microsoft.EntityFrameWorkCore (2.0.0)

### ISSUE THREAD

**Issue by BrianGSC** [JonPSmith/EfCoreInAction#2]
Had to install it maually.

**Comment by JonPSmith** [comment]
Hi @BrianGSC,

Normally I install something like `Microsoft.EntityFrameworkCore.SqlServer`, rather than `Microsoft.EntityFrameWorkCore`, as that is what I going to use. For instance the DataLayer just has `Microsoft.EntityFrameworkCore.SqlServer` installed. The database specific NuGet's then loads the other packages they need. 

So, some projects might not have `Microsoft.EntityFrameWorkCore` installed but they still work. Does that make sense?

**Comment by BrianGSC** [comment]
You are of course right. Maybe it is just a clean-up.
The Using Directive is referencing the Microsoft.EntityFrameWorkCore in severel clases.
Visual Studio registered it as an error -> build errors if not installed.
Sorry.
Regards Brian.

**Comment by JonPSmith** [comment]
Hi @BrianGSC,

No problem at all. I hope you find the repo (and book) useful.
